/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rio;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author HS SHUVO
 */
public class Rio extends javax.swing.JFrame {

    // Birds  images.
    ImageIcon im1 = new javax.swing.ImageIcon(getClass().getResource("/c1.jpg"));
    ImageIcon im2 = new javax.swing.ImageIcon(getClass().getResource("/c2.jpg"));
    ImageIcon im3 = new javax.swing.ImageIcon(getClass().getResource("/c3.jpg"));
    ImageIcon im4 = new javax.swing.ImageIcon(getClass().getResource("/c4.jpg"));
    ImageIcon im5 = new javax.swing.ImageIcon(getClass().getResource("/c5.jpg"));
    ImageIcon im6 = new javax.swing.ImageIcon(getClass().getResource("/c6.jpg"));

    ImageIcon im7 = new javax.swing.ImageIcon(getClass().getResource("/c7.jpg"));
    ImageIcon im8 = new javax.swing.ImageIcon(getClass().getResource("/c8.jpg"));
    ImageIcon im9 = new javax.swing.ImageIcon(getClass().getResource("/c9.jpg"));
    ImageIcon im10 = new javax.swing.ImageIcon(getClass().getResource("/c10.jpg"));
    ImageIcon im11 = new javax.swing.ImageIcon(getClass().getResource("/c11.jpg"));
    ImageIcon im12 = new javax.swing.ImageIcon(getClass().getResource("/c12.jpg"));
    ImageIcon im13 = new javax.swing.ImageIcon(getClass().getResource("/c13.jpg"));

    ImageIcon im14 = new javax.swing.ImageIcon(getClass().getResource("/c14.jpg"));

    // Another images.
    ImageIcon imd1 = new javax.swing.ImageIcon(getClass().getResource("/id1.jpg"));
    ImageIcon imd2 = new javax.swing.ImageIcon(getClass().getResource("/id2.jpg"));
    ImageIcon imd3 = new javax.swing.ImageIcon(getClass().getResource("/id3.jpg"));
    ImageIcon imd4 = new javax.swing.ImageIcon(getClass().getResource("/id4.jpg"));
    ImageIcon imd5 = new javax.swing.ImageIcon(getClass().getResource("/id5.jpg"));
    ImageIcon imd6 = new javax.swing.ImageIcon(getClass().getResource("/id6.jpg"));
    ImageIcon imd7 = new javax.swing.ImageIcon(getClass().getResource("/id7.jpg"));
    ImageIcon imd8 = new javax.swing.ImageIcon(getClass().getResource("/id8.jpg"));
    ImageIcon imd9 = new javax.swing.ImageIcon(getClass().getResource("/id9.jpg"));
   
    // instruction image.
    ImageIcon im = new javax.swing.ImageIcon(getClass().getResource("/Rio1.jpg"));

    private long start;
    private Timer timer;
    private boolean chromeShown;

    public Rio() {

        super("              RIO                ");

        setSize(600, 600);

        setDefaultCloseOperation(EXIT_ON_CLOSE);

        setVisible(true);

        setResizable(false);

        setLocationRelativeTo(null);

        initComponents();

        jTextField1.setText("  000 ");

        jTextField1.setEditable(false);

        jTextField2.setText(String.format("  %03d ", a));

        jTextField2.setEditable(false);

        jTextField4.setText(" 01 : 00 ");

        jTextField4.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 490));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Total Score:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 100, 108, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("High Score:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 150, 108, 32);

        jTextField1.setBackground(java.awt.Color.yellow);
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(500, 100, 90, 35);

        jTextField2.setBackground(java.awt.Color.orange);
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(500, 150, 90, 35);

        jLabel3.setBackground(new java.awt.Color(255, 255, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("TIME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 20, 90, 36);

        jButton10.setBackground(java.awt.Color.green);
        jButton10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 255));
        jButton10.setText("CREDIT");
        jButton10.setBorder(new javax.swing.border.MatteBorder(null));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(470, 280, 120, 43);

        jButton11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton11.setText("INSTRUCTION");
        jButton11.setBorder(new javax.swing.border.MatteBorder(null));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(460, 400, 130, 44);

        jButton12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton12.setText("START GAME");
        jButton12.setBorder(new javax.swing.border.MatteBorder(null));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(230, 400, 140, 44);

        jButton13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton13.setText("NEW GAME");
        jButton13.setBorder(new javax.swing.border.MatteBorder(null));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(10, 400, 130, 44);

        jTextField4.setBackground(new java.awt.Color(51, 255, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 0, 204));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(500, 20, 90, 36);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Rio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 80, 116, 81);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Rio");
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 80, 115, 81);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 255));
        jButton3.setText("Rio");
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 80, 115, 81);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 255));
        jButton4.setText("Rio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 170, 116, 80);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 255));
        jButton5.setText("Rio");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(130, 170, 115, 80);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 204, 204));
        jButton6.setText("Rio");
        getContentPane().add(jButton6);
        jButton6.setBounds(250, 170, 115, 80);

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 204, 204));
        jButton7.setText("Rio");
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 260, 116, 80);

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 204, 204));
        jButton8.setText("Rio");
        getContentPane().add(jButton8);
        jButton8.setBounds(130, 260, 115, 80);

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 204, 204));
        jButton9.setText("Rio");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(250, 260, 115, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rio 8.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int w, r, g;
    int p, q, i, l;
    int n, m, k;
    int e;
    int a1, a2, a3, a4, a5, a6, a7, a8, a9;
    int x;
    int d = 0;

    int a = 0;
    int h = 0;


    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        function();

        //do something
        // if (h == 0) {
        
        
        playSound();
        //  }
        //  h++;
    }

    private void function() {

        x = 0;

        // time.
        w = 60;

        jButton12.setEnabled(false);

        a1 = 0;
        a2 = 0;
        a3 = 0;
        a4 = 0;
        a5 = 0;
        a6 = 0;
        a7 = 0;
        a8 = 0;
        a9 = 0;

        timer = new Timer(1000, new ActionListener() {

            //  @Override  timer = new Timer(1000, new ActionListener()
            @Override
            public void actionPerformed(ActionEvent e) {

                if (chromeShown) {

                    jButton1.setIcon(null);
                    chromeShown = false;

                    jButton2.setIcon(null);
                    chromeShown = false;

                    jButton3.setIcon(null);
                    chromeShown = false;
                    jButton4.setIcon(null);
                    chromeShown = false;
                    jButton5.setIcon(null);
                    chromeShown = false;

                    jButton6.setIcon(null);
                    chromeShown = false;
                    jButton7.setIcon(null);
                    chromeShown = false;
                    jButton8.setIcon(null);
                    chromeShown = false;
                    jButton9.setIcon(null);
                    chromeShown = false;

                } else {

                    // Random function .
                    Random rand = new Random();

                    n = rand.nextInt(9) + 1;

                    Random rand1 = new Random();
                    m = rand.nextInt(9) + 1;

                    Random rand2 = new Random();
                    k = rand.nextInt(9) + 1;

                    if (m == 1 && n == 1 && k == 1) {

                        m = 1;
                        n = 6;
                        k = 7;

                    }

                    if (m == 2 && n == 2 && k == 2) {

                        m = 2;
                        n = 5;
                        k = 9;

                    }
                    if (m == 3 && n == 3 && k == 3) {

                        m = 3;
                        n = 4;
                        k = 8;

                    }
                    if (m == 4 && n == 4 && k == 4) {

                        m = 4;
                        n = 2;
                        k = 6;

                    }
                    if (m == 5 && n == 5 && k == 5) {

                        m = 5;
                        n = 1;
                        k = 3;

                    }
                    if (m == 6 && n == 6 && k == 6) {

                        m = 6;
                        n = 7;
                        k = 1;

                    }
                    if (m == 7 && n == 7 && k == 7) {

                        m = 7;
                        n = 3;
                        k = 2;

                    }
                    if (m == 8 && n == 8 && k == 8) {

                        m = 8;
                        n = 9;
                        k = 4;

                    }
                    if (m == 9 && n == 9 && k == 9) {

                        m = 9;
                        n = 8;
                        k = 5;

                    } else if (m == 1 && n == 1) {

                        m = 1;
                        n = 3;

                    } else if (m == 2 && n == 2) {

                        m = 2;
                        n = 4;

                    } else if (m == 3 && n == 3) {

                        m = 3;
                        n = 5;

                    } else if (m == 4 && n == 4) {

                        m = 4;
                        n = 6;

                    } else if (m == 5 && n == 5) {

                        m = 5;
                        n = 7;

                    } else if (m == 6 && n == 6) {

                        m = 6;
                        n = 9;

                    } else if (m == 7 && n == 7) {

                        m = 7;
                        n = 2;

                    } else if (m == 8 && n == 8) {

                        m = 8;
                        n = 1;

                    } else if (m == 9 && n == 9) {

                        m = 9;
                        n = 8;

                    } // else if (n == k) {
                    //
                    //                        n = 5;
                    //
                    //                        k = 7;
                    //
                    //                    } else if (m == k) {
                    //
                    //                        m = 5;
                    //                        k = 3;
                    //
                    //                    }
                    else if (n == 1 && k == 1) {

                        k = 1;
                        n = 3;

                    } else if (k == 2 && n == 2) {

                        k = 2;
                        n = 4;

                    } else if (k == 3 && n == 3) {

                        k = 3;
                        n = 5;

                    } else if (k == 4 && n == 4) {

                        k = 4;
                        n = 6;

                    } else if (k == 5 && n == 5) {

                        k = 5;
                        n = 7;

                    } else if (k == 6 && n == 6) {

                        k = 6;
                        n = 9;

                    } else if (k == 7 && n == 7) {

                        k = 7;
                        n = 2;

                    } else if (k == 8 && n == 8) {

                        k = 8;
                        n = 1;

                    } else if (k == 9 && n == 9) {

                        k = 9;
                        n = 8;

                    } else if (m == 1 && k == 1) {

                        m = 1;
                        k = 3;

                    } else if (m == 2 && k == 2) {

                        m = 2;
                        k = 4;

                    } else if (m == 3 && k == 3) {

                        m = 3;
                        k = 5;

                    } else if (m == 4 && k == 4) {

                        m = 4;
                        k = 6;

                    } else if (m == 5 && k == 5) {

                        m = 5;
                        k = 7;

                    } else if (m == 6 && k == 6) {

                        m = 6;
                        k = 9;

                    } else if (m == 7 && k == 7) {

                        m = 7;
                        k = 2;

                    } else if (m == 8 && k == 8) {

                        m = 8;
                        k = 1;

                    } else if (m == 9 && k == 9) {

                        m = 9;
                        k = 8;

                    }

                    // set images.
//                    if (m == 1 && n == 1 && k == 1) {
//
//                        jButton1.setIcon(im7);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 2 && n == 2 && k == 2) {
//
//                        jButton2.setIcon(imd5);
//                        chromeShown = true;
//
//                    }
//                    if (m == 3 && n == 3 && k == 3) {
//                        jButton3.setIcon(im4);
//                        chromeShown = true;
//
//                    }
//                    if (m == 4 && n == 4 && k == 4) {
//
//                        jButton4.setIcon(im2);
//                        chromeShown = true;
//                    }
//                    if (m == 5 && n == 5 && k == 5) {
//
//                        jButton5.setIcon(imd1);
//                        chromeShown = true;
//
//                    }
//                    if (m == 6 && n == 6 && k == 6) {
//
//                        jButton6.setIcon(im14);
//                        chromeShown = true;
//
//                    }
//                    if (m == 7 && n == 7 && k == 7) {
//
//                        jButton7.setIcon(im13);
//                        chromeShown = true;
//                    }
//                    if (m == 8 && n == 8 && k == 8) {
//
//                        jButton8.setIcon(imd2);
//                        chromeShown = true;
//
//                    }
//                    if (m == 9 && n == 9 && k == 9) {
//                        jButton9.setIcon(im11);
//                        chromeShown = true;
//
//                    } else if (m == 1 && n == 1) {
//                        jButton1.setIcon(im1);
//                        chromeShown = true;
//
//                    } else if (m == 2 && n == 2) {
//
//                        jButton2.setIcon(im2);
//                        chromeShown = true;
//
//                    } else if (m == 3 && n == 3) {
//
//                        jButton3.setIcon(imd7);
//                        chromeShown = true;
//
//                    } else if (m == 4 && n == 4) {
//
//                        jButton4.setIcon(im11);
//                        chromeShown = true;
//
//                    } else if (m == 5 && n == 5) {
//
//                        jButton5.setIcon(im12);
//                        chromeShown = true;
//
//                    } else if (m == 6 && n == 6) {
//
//                        jButton6.setIcon(im13);
//                        chromeShown = true;
//
//                    } else if (m == 7 && n == 7) {
//
//                        jButton7.setIcon(im14);
//                        chromeShown = true;
//
//                    } else if (m == 8 && n == 8) {
//
//                        jButton8.setIcon(im11);
//                        chromeShown = true;
//
//                    } else if (m == 9 && n == 9) {
//
//                        jButton9.setIcon(imd8);
//                        chromeShown = true;
//
//                    } else if (n == 1 && k == 1) {
//
//                        jButton1.setIcon(im11);
//                        chromeShown = true;
//
//                    } else if (k == 2 && n == 2) {
//
//                        jButton3.setIcon(im12);
//                        chromeShown = true;
//                    } else if (k == 3 && n == 3) {
//
//                        jButton2.setIcon(im13);
//                        chromeShown = true;
//
//                    } else if (k == 4 && n == 4) {
//
//                        jButton5.setIcon(im14);
//                        chromeShown = true;
//                    } else if (k == 5 && n == 5) {
//
//                        jButton4.setIcon(imd8);
//                        chromeShown = true;
//
//                    } else if (k == 6 && n == 6) {
//
//                        jButton7.setIcon(im4);
//                        chromeShown = true;
//
//                    } else if (k == 7 && n == 7) {
//
//                        jButton6.setIcon(im5);
//                        chromeShown = true;
//
//                    } else if (k == 8 && n == 8) {
//
//                        jButton8.setIcon(im6);
//                        chromeShown = true;
//
//                    } else if (k == 9 && n == 9) {
//
//                        jButton1.setIcon(imd7);
//                        chromeShown = true;
//
//                    } else if (m == 1 && k == 1) {
//
//                        jButton9.setIcon(im11);
//                        chromeShown = true;
//
//                    } else if (m == 2 && k == 2) {
//
//                        jButton2.setIcon(imd1);
//                        chromeShown = true;
//
//                    } else if (m == 3 && k == 3) {
//
//                        jButton3.setIcon(im12);
//                        chromeShown = true;
//
//                    } else if (m == 4 && k == 4) {
//
//                        jButton4.setIcon(im13);
//                        chromeShown = true;
//
//                    } else if (m == 5 && k == 5) {
//                        jButton5.setIcon(im14);
//                        chromeShown = true;
//
//                    } else if (m == 6 && k == 6) {
//
//                        jButton6.setIcon(im4);
//                        chromeShown = true;
//
//                    } else if (m == 7 && k == 7) {
//
//                        jButton7.setIcon(imd3);
//                        chromeShown = true;
//
//                    } else if (m == 8 && k == 8) {
//
//                        jButton8.setIcon(im7);
//                        chromeShown = true;
//
//                    } else if (m == 9 && k == 9) {
//
//                        jButton9.setIcon(imd9);
//                        chromeShown = true;
//
//                    }
//                    // main image.
//                    if (m == 1 && n != 5 && k != 6) {
//
//                        jButton1.setIcon(im5);
//                        chromeShown = true;
//
//                    }
//
//                    if (n == 1 && m != 3 && k != 4) {
//
//                        jButton3.setIcon(im7);
//                        chromeShown = true;
//
//                    }
//                    if (k == 1 && m != 5 && n != 8) {
//
//                        jButton5.setIcon(imd1);
//                        chromeShown = true;
//
//                    }
//                    if (n == 2 && m != 6 && k != 7) {
//
//                        jButton6.setIcon(im8);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 2 && n != 7 && k != 9) {
//
//                        jButton2.setIcon(im2);
//                        chromeShown = true;
//
//                    }
//                    if (k == 2 && m != 7 && n != 6) {
//
//                        jButton7.setIcon(imd2);
//                        chromeShown = true;
//
//                    }
//
//                    if (n == 3 && m != 4 && k != 8) {
//
//                        jButton4.setIcon(im9);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 3 && n != 1 && k != 4) {
//
//                        jButton3.setIcon(im3);
//                        chromeShown = true;
//
//                    }
//                    if (k == 3 && m != 9 && n != 4) {
//
//                        jButton9.setIcon(imd3);
//                        chromeShown = true;
//
//                    }
//
//                    if (n == 4 && k != 3 && m != 9) {
//
//                        jButton9.setIcon(im10);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 4 && n != 3 && k != 8) {
//
//                        jButton4.setIcon(im4);
//                        chromeShown = true;
//
//                    }
//                    if (k == 4 && m != 3 && n != 1) {
//
//                        jButton3.setIcon(imd4);
//                        chromeShown = true;
//
//                    }
//                    if (n == 5 && m != 1 && k != 6) {
//
//                        jButton1.setIcon(im11);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 5 && k != 1 && n != 8) {
//
//                        jButton5.setIcon(im5);
//                        chromeShown = true;
//
//                    }
//                    if (k == 5 && m != 8 && n != 9) {
//
//                        jButton8.setIcon(imd5);
//                        chromeShown = true;
//
//                    }
//                    if (n == 6 && k != 2 && m != 7) {
//
//                        jButton7.setIcon(im12);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 6 && n != 2 && k != 7) {
//
//                        jButton6.setIcon(im6);
//                        chromeShown = true;
//
//                    }
//                    if (k == 6 && m != 1 && n != 5) {
//
//                        jButton1.setIcon(imd6);
//                        chromeShown = true;
//
//                    }
//                    if (n == 7 && m != 2 && k != 9) {
//
//                        jButton2.setIcon(im13);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 7 && n != 6 && k != 2) {
//
//                        jButton7.setIcon(im7);
//                        chromeShown = true;
//
//                    }
//                    if (k == 7 && m != 6 && n != 2) {
//
//                        jButton6.setIcon(imd6);
//                        chromeShown = true;
//
//                    }
//                    if (n == 8 && m != 5 && k != 1) {
//
//                        jButton5.setIcon(im14);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 8 && n != 9 && k != 5) {
//
//                        jButton8.setIcon(im8);
//                        chromeShown = true;
//
//                    }
//                    if (k == 8 && m != 4 && n != 3) {
//
//                        jButton4.setIcon(imd8);
//                        chromeShown = true;
//
//                    }
//                    if (n == 9 && m != 9 && k != 5) {
//
//                        jButton8.setIcon(im12);
//                        chromeShown = true;
//
//                    }
//
//                    if (m == 9 && n != 4 && k != 3) {
//
//                        jButton9.setIcon(im9);
//                        chromeShown = true;
//
//                    }
//                    if (k == 9 && m != 2 && n != 7) {
//
//                        jButton2.setIcon(imd9);
//                        chromeShown = true;
//
//                    }
                    
                      if (m == 1 || n == 1 || k == 1) {
                        jButton1.setIcon(im2);
                        chromeShown = true;

                    }

                    if (m == 2 || n == 2 || k == 2) {
                        jButton2.setIcon(imd2);
                        chromeShown = true;

                    }

                    if (m == 3 || n == 3 || k == 3) {
                        jButton3.setIcon(im3);
                        chromeShown = true;

                    }

                    if (m == 4 || n == 4 || k == 4) {
                        jButton4.setIcon(im2);
                        chromeShown = true;

                    }
                    if (m == 5 || n == 5 || k == 5) {
                        jButton5.setIcon(im6);
                        chromeShown = true;

                    }
                    if (m == 6 || n == 6 || k == 6) {
                        jButton6.setIcon(imd1);
                        chromeShown = true;

                    }
                    if (m == 7 || n == 7 || k == 7) {
                        jButton7.setIcon(im4);
                        chromeShown = true;
                    }
                    if (m == 8 || n == 8 || k == 8) {
                        jButton8.setIcon(im5);
                        chromeShown = true;

                    }
                    if (m == 9 || n == 9 || k == 9) {
                        jButton9.setIcon(im6);
                        chromeShown = true;

                    }
                    jButton1.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton1ActionPerformed(evt);
                        }

                        private void jButton1ActionPerformed(ActionEvent evt) {
                            a1 = 1;
                        }
                    });

                    jButton2.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton2ActionPerformed(evt);
                        }

                        private void jButton2ActionPerformed(ActionEvent evt) {
                            a2 = 1;
                        }
                    });

                    jButton3.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton3ActionPerformed(evt);
                        }

                        private void jButton3ActionPerformed(ActionEvent evt) {
                            a3 = 1;

                        }

                    });

                    jButton4.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton4ActionPerformed(evt);
                        }

                        private void jButton4ActionPerformed(ActionEvent evt) {
                            a4 = 1;
                        }

                    });

                    jButton5.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton5ActionPerformed(evt);
                        }

                        private void jButton5ActionPerformed(ActionEvent evt) {
                            a5 = 1;

                        }

                    });

                    jButton6.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton6ActionPerformed(evt);
                        }

                        private void jButton6ActionPerformed(ActionEvent evt) {
                            a6 = 1;
                        }

                    });

                    jButton7.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton7ActionPerformed(evt);
                        }

                        private void jButton7ActionPerformed(ActionEvent evt) {

                            a7 = 1;

                        }

                    });

                    jButton8.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton8ActionPerformed(evt);
                        }

                        private void jButton8ActionPerformed(ActionEvent evt) {
                            a8 = 1;

                        }

                    });

                    jButton9.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            jButton9ActionPerformed(evt);
                        }

                        private void jButton9ActionPerformed(ActionEvent evt) {
                            a9 = 1;

                        }

                    });

                }

                // score add.
//                if (a1 == 1 && m == 1 && n == 1 && k == 1) {
//
//                    playSound6();
//                    x = x + 5;
//
//                }
//
//                if (a2 == 1 && m == 2 && n == 2 && k == 2) {
//
//                    playSound7();
//                    x = x - 5;
//
//                }
//                if (a3 == 1 && m == 3 && n == 3 && k == 3) {
//
//                    playSound6();
//                    x = x + 5;
//
//                }
//                if (a4 == 1 && m == 4 && n == 4 && k == 4) {
//
//                    playSound6();
//                    x = x + 5;
//                }
//                if (a5 == 1 && m == 5 && n == 5 && k == 5) {
//
//                    playSound7();
//                    x = x - 5;
//
//                }
//                if (a6 == 1 && m == 6 && n == 6 && k == 6) {
//
//                    playSound6();
//                    x = x + 5;
//
//                }
//                if (a7 == 1 && m == 7 && n == 7 && k == 7) {
//                    playSound6();
//                    x = x + 5;
//                }
//                if (a8 == 1 && m == 8 && n == 8 && k == 8) {
//
//                    playSound7();
//                    x = x - 5;
//
//                }
//
//                if (a9 == 1 && m == 9 && n == 9 && k == 9) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a1 == 1 && m == 1 && n == 1) {
//
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a2 == 1 && m == 2 && n == 2) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a3 == 1 && m == 3 && n == 3) {
//
//                    playSound7();
//                    x = x - 5;
//
//                } else if (a4 == 1 && m == 4 && n == 4) {
//
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a5 == 1 && m == 5 && n == 5) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a6 == 1 && m == 6 && n == 6) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a7 == 1 && m == 7 && n == 7) {
//                    playSound6();
//
//                    x = x + 5;
//
//                } else if (a8 == 1 && m == 8 && n == 8) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a9 == 1 && m == 9 && n == 9) {
//                    playSound7();
//                    x = x - 5;
//
//                } else if (a1 == 1 && n == 1 && k == 1) {
//
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a3 == 1 && k == 2 && n == 2) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a2 == 1 && k == 3 && n == 3) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a5 == 1 && k == 4 && n == 4) {
//                    playSound6();
//                    x = x + 5;
//                } else if (a4 == 1 && k == 5 && n == 5) {
//                    playSound7();
//                    x = x - 5;
//                } else if (a7 == 1 && k == 6 && n == 6) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a6 == 1 && k == 7 && n == 7) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a8 == 1 && k == 8 && n == 8) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a1 == 1 && k == 9 && n == 9) {
//                    playSound7();
//                    x = x - 5;
//
//                } else if (a9 == 1 && m == 1 && k == 1) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a2 == 1 && m == 2 && k == 2) {
//                    playSound7();
//                    x = x - 5;
//
//                } else if (a3 == 1 && m == 3 && k == 3) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a4 == 1 && m == 4 && k == 4) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a5 == 1 && m == 5 && k == 5) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a6 == 1 && m == 6 && k == 6) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a7 == 1 && m == 7 && k == 7) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a8 == 1 && m == 8 && k == 8) {
//                    playSound6();
//                    x = x + 5;
//
//                } else if (a9 == 1 && m == 9 && k == 9) {
//                    playSound7();
//                    x = x - 5;
//
//                }

                if ((a1 == 1) && (n == 1 || m == 1 || k == 1)) {
                    playSound6();
                    x = x + 5;
                }
                if ((a2 == 1) && (n == 2 || m == 2 || k == 2)) {
                    playSound7();
                    x = x - 5;
                }
                if ((a3 == 1) && (n == 3 || m == 3 || k == 3)) {
                    playSound6();
                    x = x + 5;
                }
                if ((a4 == 1) && (n == 4 || m == 4 || k == 4)) {
                    playSound6();
                    x = x + 5;
                }
                if ((a5 == 1) && (n == 5 || m == 5 || k == 5)) {
                    playSound6();
                    x = x + 5;
                }
                if ((a6 == 1) && (n == 6 || m == 6 || k == 6)) {
                    playSound7();
                    x = x - 5;
                }
                if ((a7 == 1) && (n == 7 || m == 7 || k == 7)) {
                    playSound6();
                    x = x + 5;
                }
                if ((a8 == 1) && (n == 8 || m == 8 || k == 8)) {
                    playSound6();
                    x = x + 5;
                }
                if ((a9 == 1) && (n == 9 || m == 9 || k == 9)) {
                    playSound6();
                    x = x + 5;
                }

                w--;

                // time.
                jTextField4.setText(String.format(" 00 : %02d ", w));

                // total score.
                jTextField1.setText(String.format("  %03d ", x));

                if (x > a) {
                    a = x;

                }

                // high score.
                jTextField2.setText(String.format("  %03d ", a));

                if (w == 00) {

                    jTextField4.setText(" 01 : 00 ");

                    jButton12.setEnabled(true);

                    jButton1.setIcon(null);
                    chromeShown = true;

                    jButton2.setIcon(null);
                    chromeShown = true;

                    jButton3.setIcon(null);
                    chromeShown = true;
                    jButton4.setIcon(null);
                    chromeShown = true;
                    jButton5.setIcon(null);
                    chromeShown = true;

                    jButton6.setIcon(null);
                    chromeShown = true;
                    jButton7.setIcon(null);
                    chromeShown = true;
                    jButton8.setIcon(null);
                    chromeShown = true;
                    jButton9.setIcon(null);
                    chromeShown = true;

                }

                if (w == 00) {

                    timer.stop();

                }

                a1 = 0;
                a2 = 0;
                a3 = 0;
                a4 = 0;
                a5 = 0;
                a6 = 0;
                a7 = 0;
                a8 = 0;
                a9 = 0;

            }

        });

        jTextField4.setText(" 01 : 00 ");

        jTextField1.setText("  000 ");

        jTextField2.setText(String.format("  %03d ", a));

        timer.start();

        // this.getContentPane().add(panel);
        this.setVisible(true);

        start = System.currentTimeMillis();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

                new Rio().setVisible(true);

            }

        });
    }//GEN-LAST:event_jButton12ActionPerformed


    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        playSound2();

        JOptionPane.showMessageDialog(null, " NAME:-  BIDHAN BISWAS , REG:- 2012331536 . \n\n NAME:- HOSSAIN SHAHID SOROARDI , REG:- 2012331544 .\n\n  NAME:-  AHSANUR RABBI RAHAT , REG:- 2012331507 .", " ***  < 'CREDIT' > *** ", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jButton10ActionPerformed


    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        playSound2();

        JOptionPane.showMessageDialog(null, " 1. Click the birds and get more scores . \n\n 2. Another symbol click,then score will be deducted. \n\n 3. Time is 1:00 minute.\n\n 4.So try quickly and have fun . ", " ***  < 'INSTRUCTION' > *** ", JOptionPane.PLAIN_MESSAGE, im);


    }//GEN-LAST:event_jButton11ActionPerformed

    public void playSound() {
        try {

            InputStream inputStream = getClass().getResourceAsStream("/new.wav");
            AudioStream audioStream = new AudioStream(inputStream);
            AudioPlayer.player.start(audioStream);
        } catch (IOException e) {

        }
    }

    public void playSound1() {
        try {

            InputStream inputStream = getClass().getResourceAsStream("/audio1.wav");
            AudioStream audioStream = new AudioStream(inputStream);
            AudioPlayer.player.start(audioStream);
        } catch (IOException e) {

        }
    }

    public void playSound2() {
        try {

            InputStream inputStream = getClass().getResourceAsStream("/audio.wav");
            AudioStream audioStream = new AudioStream(inputStream);
            AudioPlayer.player.start(audioStream);
        } catch (IOException e) {

        }
    }

    public void playSound5() {
        try {

            InputStream inputStream = getClass().getResourceAsStream("/click.wav");
            AudioStream audioStream = new AudioStream(inputStream);
            AudioPlayer.player.start(audioStream);
        } catch (IOException e) {

        }
    }

    public void playSound6() {
        try {

            InputStream inputStream = getClass().getResourceAsStream("/bird.wav");
            AudioStream audioStream = new AudioStream(inputStream);
            AudioPlayer.player.start(audioStream);
        } catch (IOException e) {

        }
    }

    public void playSound7() {
        try {

            InputStream inputStream = getClass().getResourceAsStream("/tiger.wav");
            AudioStream audioStream = new AudioStream(inputStream);
            AudioPlayer.player.start(audioStream);
        } catch (IOException e) {

        }
    }


    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        // TODO add your handling code here:
        playSound1();

        timer.stop();

        jButton12.setEnabled(true);

        jTextField4.setText(" 01 : 00 ");

        jTextField1.setText("  000 ");

        jTextField2.setText(String.format("  %03d ", a));

        jButton1.setIcon(null);
        chromeShown = true;

        jButton2.setIcon(null);
        chromeShown = true;

        jButton3.setIcon(null);
        chromeShown = true;

        jButton4.setIcon(null);
        chromeShown = true;

        jButton5.setIcon(null);
        chromeShown = true;

        jButton6.setIcon(null);
        chromeShown = true;

        jButton7.setIcon(null);
        chromeShown = true;

        jButton8.setIcon(null);
        chromeShown = true;

        jButton9.setIcon(null);
        chromeShown = true;


    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
